const BASE_IPFS_URI = 'ipfs://QmadB7RnpfXSd2JX1e6HZLBKwSkBR3PiXhTmkN9dE5DKur';

// Collection metadata
const CHUNKY_METADATA = BASE_IPFS_URI + '/chunkies/collection.json';
const CHUNKY_ITEM_METADATA = BASE_IPFS_URI + '/items/collection.json';

// Catalog
const CHUNKY_CATALOG_METADATA = BASE_IPFS_URI + '/catalog/metadata.json';
const CHUNKY_CATALOG_TYPE = 'image/*';
const CHUNKY_ITEM_LEFT_SLOT_METADATA = BASE_IPFS_URI + 'catalog/slots/item-left.json';
const CHUNKY_ITEM_RIGHT_SLOT_METADATA = BASE_IPFS_URI + 'catalog/slots/item-right.json';

// Items metadata
const CHUNKY_ITEM_BASE_METADATA_URI = BASE_IPFS_URI + 'items/';

// FIXED PARTS
const CHUNKY_V1_HEAD_FIXED_PART_ID = 1;
const CHUNKY_V1_BODY_FIXED_PART_ID = 2;
const CHUNKY_V1_HANDS_FIXED_PART_ID = 3;
const CHUNKY_V2_HEAD_FIXED_PART_ID = 4;
const CHUNKY_V2_BODY_FIXED_PART_ID = 5;
const CHUNKY_V2_HANDS_FIXED_PART_ID = 6;
const CHUNKY_V3_HEAD_FIXED_PART_ID = 7;
const CHUNKY_V3_BODY_FIXED_PART_ID = 8;
const CHUNKY_V3_HANDS_FIXED_PART_ID = 9;
const CHUNKY_V4_HEAD_FIXED_PART_ID = 10;
const CHUNKY_V4_BODY_FIXED_PART_ID = 11;
const CHUNKY_V4_HANDS_FIXED_PART_ID = 12;

// SLOT PARTS
const CHUNKY_LEFT_HAND_SLOT_PART_ID = 1001;
const CHUNKY_RIGHT_HAND_SLOT_PART_ID = 1002;

// PART TYPES (Defined by standard)
const PART_TYPE_SLOT = 1;
const PART_TYPE_FIXED = 2;

// Z INDEXES
const Z_INDEX_BODY = 2;
const Z_INDEX_HEAD = 4;
const Z_INDEX_HAND_ITEMS = 6;
const Z_INDEX_HANDS = 8;

// Equippable groups
const EQUIPPABLE_GROUP_FOR_CHUNKIES_DEFAULT = 1; // Only in case we want all chunkies to be later equippable into something
const EQUIPPABLE_GROUP_FOR_ITEMS_LEFT_HAND = CHUNKY_LEFT_HAND_SLOT_PART_ID;
const EQUIPPABLE_GROUP_FOR_ITEMS_RIGHT_HAND = CHUNKY_RIGHT_HAND_SLOT_PART_ID;

export {
  BASE_IPFS_URI,
  CHUNKY_METADATA,
  CHUNKY_ITEM_METADATA,
  CHUNKY_CATALOG_METADATA,
  CHUNKY_CATALOG_TYPE,
  CHUNKY_V1_HEAD_FIXED_PART_ID,
  CHUNKY_V1_BODY_FIXED_PART_ID,
  CHUNKY_V1_HANDS_FIXED_PART_ID,
  CHUNKY_V2_HEAD_FIXED_PART_ID,
  CHUNKY_V2_BODY_FIXED_PART_ID,
  CHUNKY_V2_HANDS_FIXED_PART_ID,
  CHUNKY_V3_HEAD_FIXED_PART_ID,
  CHUNKY_V3_BODY_FIXED_PART_ID,
  CHUNKY_V3_HANDS_FIXED_PART_ID,
  CHUNKY_V4_HEAD_FIXED_PART_ID,
  CHUNKY_V4_BODY_FIXED_PART_ID,
  CHUNKY_V4_HANDS_FIXED_PART_ID,
  CHUNKY_LEFT_HAND_SLOT_PART_ID,
  CHUNKY_RIGHT_HAND_SLOT_PART_ID,
  PART_TYPE_SLOT,
  PART_TYPE_FIXED,
  Z_INDEX_BODY,
  Z_INDEX_HEAD,
  Z_INDEX_HAND_ITEMS,
  Z_INDEX_HANDS,
  EQUIPPABLE_GROUP_FOR_CHUNKIES_DEFAULT,
  EQUIPPABLE_GROUP_FOR_ITEMS_LEFT_HAND,
  EQUIPPABLE_GROUP_FOR_ITEMS_RIGHT_HAND,
  CHUNKY_ITEM_LEFT_SLOT_METADATA,
  CHUNKY_ITEM_RIGHT_SLOT_METADATA,
  CHUNKY_ITEM_BASE_METADATA_URI,
};
